services:
  dbadesup:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - test-db:/var/lib/mysql
    networks:
      - wpsite-test

  wordpress:
    image: wordpress:6.8.3
    depends_on:
      - dbadesup
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: dbadesup:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wpsite-test


networks:
  wpsite-test:

volumes:
  test-db:
